# start by pulling the python image
FROM python:3.9-alpine

# copy the requirements file into the image
COPY requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy everything else from the local file to the image
COPY . /app

# expose the port
EXPOSE 5250

# specify the command to run on container start
CMD ["flask", "run","-h","0.0.0.0","-p","5250"]